version: "3.8"

services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.33.0
    restart: unless-stopped
    ports:
      - 8080:8080
      - 50051:50051
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: text2vec-openai
      ENABLE_MODULES: text2vec-openai
      OPENAI_APIKEY: ${OPENAI_API_KEY}
      CLUSTER_HOSTNAME: "node1"
    volumes:
      - weaviate_data:/var/lib/weaviate

  localstack:
    image: localstack/localstack:4.13.0
    container_name: localstack
    restart: unless-stopped
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb,sqs,lambda,iam
      - DEBUG=1
      - PERSISTENCE=1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=ap-south-1
      - HOSTNAME_EXTERNAL=${LOCALSTACK_HOST:-localhost}
      - EXTRA_CORS_ALLOWED_ORIGINS=http://localhost:5173,https://paralegal.vishesh-dugar.me,https://vishesh-dugar.me
      - S3_SKIP_SIGNATURE_VALIDATION=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - localstack_data:/var/lib/localstack
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    profiles: [dev]
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
      - AWS_REGION=ap-south-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    depends_on:
      - localstack

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redisinsight:
    image: redis/redisinsight:latest
    profiles: [dev]
    restart: unless-stopped
    ports:
      - "5540:5540"
    environment:
      - RI_REDIS_HOST=redis
      - RI_REDIS_PORT=6379
      - RI_REDIS_ALIAS=Paralegal-Redis
    depends_on:
      - redis

volumes:
  weaviate_data:
  localstack_data:
  redis_data:
