name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          command_timeout: 10m
          script: |
            export BUN_INSTALL="$HOME/.bun"
            export PATH="$BUN_INSTALL/bin:$PATH"
            export PATH="$PATH:$HOME/.npm-global/bin"

            rm -rf ~/paralegal && git clone https://github.com/${{ github.repository }} ~/paralegal
            cd ~/paralegal

            chmod +x ./scripts/setup-localstack.sh
            CI=true OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} ./scripts/setup-localstack.sh
            export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            pm2 start src/common/run-with-env.ts \
              --name "paralegal-app" \
              --interpreter bun \
              --update-env \
              -- config/local.json src/index.ts || \
            pm2 restart "paralegal-app" --update-env
